server:
  port: 8989  #端口号
  servlet:
    context-path: /cmfz   #项目名称
    jsp:
      init-parameters:
        development: true  #开启热部署

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfz
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


mybatis:
  mapper-locations: classpath:com/baizhi/jbc/Dao/*Mapper.xml
  type-aliases-package: com.baizhi.jbc.entity
